services:
  pdf-translator:
    build:
      context: .
      dockerfile: Dockerfile
      target: production-stage
    container_name: pdf-translator-app
    ports:
      - "8888:80"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    networks:
      - pdf-network

networks:
  pdf-network:
    driver: bridge 